### ISSUE TITLE
auth_totp wrong secret code in wizard

### ISSUE THREAD

**Issue by travish2** [OCA/server-auth#140]
Tested on v11 and v12 runbot, unable to test on v10/v9

When opening the wizard to add a new MFA device the secret code (and QR code) displayed is not the same as the secret code used to validate.

After entering any Confirmation Code and clicking Create, the secret code and QR code reloads and shows the correct code. If this is not noticed by user they continue entering the 6 digit code from the first secret and continue receiving validation errors.

Workaround: Enter any 6 digit code and click validate, then add the displayed secret code / QR to authenticator

**Comment by ProgrammedByJake** [comment]
In v11 this can be fixed by adding force_save="1" to the secret key field.

I don't believe this feature exists in v10, so another approach will be needed.
Creating the record in python before opening it would solve it, albeit not very elegantly.

I'll play around tonight and make a PR if I find a solution.

**Comment by tom-aspire** [comment]
I'm on v12, the workaround that @travish2 suggested works.  I tried adding the force_save="1" parameter to the secret key field, need to do some more testing but that seems to not have fixed the problem for us and also may have broken the workaround.

**Comment by max3903** [comment]
@patrickrwilson Here is the issue with capturing the QR code I told you about. It has 2 open pull requests fixing it.
