### ISSUE TITLE
Password vault

### ISSUE THREAD

**Issue by rousseldenis** [OCA/server-auth#222]
To help teams to collaborate, sometimes it is needed to share identifications (websites,...) on some light organizations.

Does anybody ever implemented such 'Vault'? Do you think it's a good idea ?

**Comment by fredrikarvas-vertel** [comment]
Hi @rousseldenis 

Yes it is a good idea. 
1 
Here are two tools we use at Vertel
https://www.freeipa.org/ on all our internally hosted servers (dev, test, staging and production servers). 

2 On a previous company we used a local password file with Keypass. 
That is kept on a single server and we have a key-file we change every time someone left the company.

3 When we share a password we use https://pwpush.com/ instead of shareing a password in email or a chat software. 

4 A collegue is developing a vault - https://libraries.io/pypi/acid-vault which has great solutions for these issues.

I hope this helped.
/Fredrik

**Comment by rousseldenis** [comment]
@fredrikarvas-vertel thanks for the pointers. But guys from initos have developed a module for that here.

https://github.com/OCA/server-auth/tree/14.0/vault

I close this

**Comment by fredrikarvas-vertel** [comment]
Thanks!
