### ISSUE TITLE
Auth error causing loop when automatic provider is enabled

### ISSUE THREAD

**Issue by sebastien-weiland** [OCA/server-auth#380]
## Module
saml auth

## Describe the bug
When enabling automatic SAM provider selection, if the auth is NOT successful, the auth mechanism should not LOOP

## To Reproduce
**Affected versions**: v15

1. Enable automatic SAML provider
2. Take a valid SAML auth, put an error in the identifier so that the person is not able to authenticate
3. Try to access again
4. Endless loop and you never see the logon error

**Expected behavior**
Should display an error and stop there after 1st error (no point looping).

**Comment by obayit** [comment]
I am facing a similar issue but I am not using the `SAML` module, or any custom auth modules.
The loop happens when visiting `/web/login` with an expired token.
I can't figure out exactly what is happening, but after tracing the call stack with a lot of `print` statements,

I found out that the `SessionExpiredException` is being raised in the `/web/login` page! which should not happen because otherwise, how is the user going to login?

A workaround is modifying the begining of `_auth_timeout_check` to:
```
    def _auth_timeout_check(self, auth_method):
        """Perform session timeout validation and expire if needed."""

        if not http.request or auth_method == 'public':
            return
``` 

Also calling it from the `ir.http` method `_authenticate` like this:
```
    def _authenticate(cls, auth_method='user'):
        res = super(IrHttp, cls)._authenticate(auth_method=auth_method)
        if request and request.env and request.env.user:
            request.env.user._auth_timeout_check(auth_method)
        return res
```

**Edit**
This also requires making sure the route for `/web/login` is public, sometimes it is set to `"none"`.
```
    @http.route(auth='public`)
    def web_login(self, *args, **kw):
```

**Edit 2**
The issue I am facing is with `auth_session_timeout`
