### ISSUE TITLE
[13.0] vault: Loosing keys when deleting a user from vault

### ISSUE THREAD

**Issue by CarlosRoca13** [OCA/server-auth#415]
TT38783

ping @pedrobaeza @fkantelberg 

In module vault (at least in v13), as the title says, when we delete some user from an existing vault with entries, the values added on this entries cannot be accessed. We do not know if this is a bug or a situation that requires an action.

You can see what is happening in next gif:
![vault_bug](https://user-images.githubusercontent.com/35952655/188126640-6ebc2695-edf7-49ec-bd86-c03befafff5c.gif)

**Comment by fkantelberg** [comment]
This is a bug in all versions because the fields are invisible and aren't loaded into the JS localdata. It causes that the keys of the users are recreated (atleast the first 40) and afterwards you can't decrypt because the master keys doesn't fit for the not changed field and file data. I had to rework the entire re-encryption process because of other problems I noticed while working on it.

Can you review the branches for 13.0 and 14.0? #416 #417

**Comment by pedrobaeza** [comment]
Closing as fixed.
