### ISSUE TITLE
Unable to install module "auth_oidc" because an external dependency is not met: Python library not installed: python-jose

### ISSUE THREAD

**Issue by bomb-kst** [OCA/server-auth#528]
Dear Team,

I've already installed [python-jose](https://pypi.org/project/python-jose/) via a command `pip install python-jose` on the host server and then restart the server. But I don't know why I still got this error.

I want to install Authentication OpenID Connect module to connect with auth0

 OS : Ubuntu 20.04.5 LTS
 Python :
 `python --version` => Python 2.7.18
 `python3 --version` => Python 3.8.10
`pip --version` => pip 23.0 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
 
 Please give me any ideas to solve this issue.

**Comment by jcolley** [comment]
> Dear Team,
> 
> I've already installed [python-jose](https://pypi.org/project/python-jose/) via a command `pip install python-jose` on the host server and then restart the server. But I don't know why I still got this error.

Try installing the python-jose package with the (admittedly less-conventional) install string provided by the installation section of the documentation here: https://pypi.org/project/python-jose/
Be sure to pay close attention to the instruction section rather than copy/pasting the string located at the top of the page...

**Comment by slysiou** [comment]
You say "host server", So, I suppose you are using container.
In this case, you must install `python-jose` in the image.

Example of Dockerfile:
```
FROM odoo:16

RUN python3 -m pip install  python-jose
```
