### ISSUE TITLE
[11] Password Security - Reset password

### ISSUE THREAD

**Issue by MathAndrews** [OCA/server-auth#54]
Hi,

I install the password_security, and I'm not sure that the test for the "resets inside of min" is working.
I'm on Odoo 11, and the reset password form send in "qcontext" a empty string for the token as so the first 'if' is never valid. (controller/main.py line 61)
Plus, if this 'if' is valid the queries "user_ids = request.env.sudo().search(...)" (line 74 and 79) are not valid and throw an exception "AttributeError: 'Environment' object has no attribute 'sudo'" and should be replace by "user_ids = request.env['res.users'].sudo().search(...)"

Best regards,

M.

**Comment by pedrobaeza** [comment]
Can you express some steps for reproducing a problem?

**Comment by MathAndrews** [comment]
Hi,

1. Token in qcontext variable:
- add logs to display _qcontext_ variable (controller/main.py line 66)
- go to "/web/reset_password" page
- submit the form
- in the logs you will see something like: "OrderedDict([('login', 'math@aaa.com'), ('redirect', ''), ('token', ''), ('reset_password_enabled', True), ('signup_enabled', True)])"

So the condition _'token' not in qcontext_ in the is statement is always False

2. Exception "AttributeError: 'Environment' object has no attribute 'sudo'"
- make sure the IF statement is True (controller/main.py line 67)
- go to "/web/reset_password" page
- submit the form
- you will get the Exception

**Comment by pedrobaeza** [comment]
But I still don't see the problem in the standard module. Are you adding some custom code or something?

**Comment by MathAndrews** [comment]
For me the issue is as the test **'token' not in qcontext** is always **False**, so it will not do the check done by **user_ids._validate_pass_reset()**

I try on a brand new database, and install the module "auth_signup", "base_setup", "contacts", "website", and "password_security"

**Comment by MathAndrews** [comment]
Hi,
Any news about this? Do I misunderstand something?

**Comment by raishak6** [comment]
I installed the module on Version 10 and it worked fine. However, I noticed that after password expires, based on the expiration period specified, no user (including the Administrator) would be able to login again and no one (including the Administrator) is redirected to the password reset page. If the Admin can be excluded from the password constrain and the users are redirected to the password reset page, then all will be fine. Otherwise, everyone, including the Admin might no longer have access after password expiration. Is there a way to resolve this?

**Comment by evaldezb** [comment]
## I'm having the same (or similar) issue.

If the user password has expired:
```python
days = (today - write_date).days
return days > self.company_id.password_expiration  # True
```
Then, instead of readirecting to the reset password form, it will say: `Invalid signup token`.

But then I noticed, that the token changes every time the user tries to log in with the expired password, for example:

## After the user tries to log in with the correct (expired) password:
![image](https://user-images.githubusercontent.com/32545163/93150461-349f4780-f6c7-11ea-8f36-54298e8640f6.png)

## With the `admin` user I go to the user form, the token has changed:
![image](https://user-images.githubusercontent.com/32545163/93150585-965fb180-f6c7-11ea-94e0-d547d2594f52.png)

## If I try to log in with the user again, the token changes again
![image](https://user-images.githubusercontent.com/32545163/93150712-e9396900-f6c7-11ea-9709-7dc48d9b0b5b.png)

## New Token (for some reason)
![image](https://user-images.githubusercontent.com/32545163/93150794-1ede5200-f6c8-11ea-8815-f2429a37e404.png)

> Some help would be appreciated 😃

**Comment by LJared** [comment]
> ## I'm having the same (or similar) issue.
> 
> If the user password has expired:
> 
> ```python
> days = (today - write_date).days
> return days > self.company_id.password_expiration  # True
> ```
> 
> Then, instead of readirecting to the reset password form, it will say: `Invalid signup token`.
> 
> But then I noticed, that the token changes every time the user tries to log in with the expired password, for example:
> ## After the user tries to log in with the correct (expired) password:
> 
> ![image](https://user-images.githubusercontent.com/32545163/93150461-349f4780-f6c7-11ea-8f36-54298e8640f6.png)
> ## With the `admin` user I go to the user form, the token has changed:
> 
> ![image](https://user-images.githubusercontent.com/32545163/93150585-965fb180-f6c7-11ea-94e0-d547d2594f52.png)
> ## If I try to log in with the user again, the token changes again
> 
> ![image](https://user-images.githubusercontent.com/32545163/93150712-e9396900-f6c7-11ea-9709-7dc48d9b0b5b.png)
> ## New Token (for some reason)
> 
> ![image](https://user-images.githubusercontent.com/32545163/93150794-1ede5200-f6c8-11ea-8815-f2429a37e404.png)
> 
> > Some help would be appreciated 😃

Hello @evaldezb were you able to find a solution for that issue?
