### ISSUE TITLE
Redirect back to log in page

### ISSUE THREAD

**Issue by 1StreamSteve** [OCA/server-auth#562]
Is there a way to change the redirect URL so that users dont land back on the login page looking at the Username and Password prompt?

Clients log in, the module redirects and the authentication process goes well. however when returned the module is putting the user back to the login page looking at the username and password page. So they think they haven't logged in.

Is there a way to customize this so it can land on something like the Discuss page like the default odoo behaviour does.

Thanks!

**Comment by legalsylvain** [comment]
Hi. You are talking about witch module ?
Thanks.

**Comment by 1StreamSteve** [comment]
The saml module, when you authenticate in Azure, it redirects you back. You are logged in because the drop down is available on the top left to go to different modules, but users still see the Odoo username and password page. This is a bit confusing for users that are not computer literate and I've had several clients ask if we can set the return page to a module like Projects or something.

**Comment by legalsylvain** [comment]
@vincent-hatakeyama : could you take a look on this one ?

**Comment by vincent-hatakeyama** [comment]
That’s not how the module works. Like auth_oauth, the module does not force the return page to be /web/login. The standard page displayed is the same as the one after a user and password login.

You either have misconfigured the identity provider to force the return page in some way, or misconfigured something in odoo. If you use the autoredirect, do not provide a link to /web/login, otherwise when the user comes back from the identity provider, that page would be displayed again; just point to /web or the root URL instead.

**Comment by legalsylvain** [comment]
Thanks for the explanation @vincent-hatakeyama !
